### ISSUE TITLE
Combine "Claim" and "Withdraw" on the Farms page

### ISSUE THREAD

**Issue by kcole16** [ref-finance/ref-ui#101] opened 2021-06-21 21:16 UTC
### Overview

Once #97 is implemented, there is no reason to have both "Claim" and "Withdraw" actions in Farming. Instead, there should be one button "Claim", which should both claim the tokens on the user's behalf, and withdraw them.

### Acceptance Criteria
- [x] There is no "Withdraw" button
- [x] Selecting the "Claim" button for a specific farm claims and withdraws the tokens to the user's account
- [ ] Remove "Claim" from the side menu, so users must claim each token individual

**Comment by kcole16** [comment] 2021-06-21 21:16
Thoughts on this @aidai524 @marco-sundsk?

**Comment by marco-sundsk** [comment] 2021-06-22 12:59
> ### Overview
> Once #97 is implemented, there is no reason to have both "Claim" and "Withdraw" actions in Farming. Instead, there should be one button "Claim", which should both claim the tokens on the user's behalf, and withdraw them.
> 
> ### Acceptance Criteria
> * [x]  There is no "Withdraw" button
> * [x]  Selecting the "Claim" button for a specific farm claims and withdraws the tokens to the user's account
> * [ ]  Selecting the "Claim" for all farms claims and withdraws the tokens for all farms

* For Criteria 1, It is something like issue#97, transferring token to user account has a chance to fail. It may caused by haven't been register to token contract, beside that it also may be because temporary network problem. When transfer fails, the token will be no place to go if not going to the inner account in farming contract. So, the withdraw button should be kept somewhere for this scenario to let user has a way to withdraw them later. 
* For criteria 2, it can be supported by contract backend in next version, I will merge claim and withdraw into one interface, and if encounter any problem when transferring token, the token goes to user's inner account and waiting for user to withdraw it explicitly.
* For criteria 3, the backend would provide two interfaces, one is to claim all farms reward, the other is to withdraw all reward claimed. Then frontend can combine those two invoke into one batch action. But, as long as any problem occurs at transfer token step, the token will goes to inner account.

**Closed** 2022-03-23 02:39 UTC
